server:
  port: 8085

spring:
  application:
    name: order-management
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/order-management
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    config:
      loadbalancer:
        ribbon:
          enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
